name: Build, Pack & Publish

on:
  create:
    branches:
      - release/**
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Get Build Version
        run: |
            Import-Module ./build/GetBuildVersion.psm1
            Write-Host $Env:GITHUB_REF
            $version = GetBuildVersion -VersionString $Env:GITHUB_REF
            echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
      - name: Run the build script
        uses: cake-build/cake-action@v1
        with:
          script-path: build.cake
          target: Pack
          cake-bootstrap: true
      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: code_coverage/results.info
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Solnet-Serum-${{ env.BUILD_VERSION }}-${{ github.sha }}
          path: Solnet.Serum/bin/Release/net5.0/ref/
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: Solnet.Serum/bin/Release/net5.0/ref/Solnet.Serum.dll
          tag: ${{ env.BUILD_VERSION }}
      - name: Publish on version change
        id: publish_nuget
        uses: bmresearch/publish-nuget@master
        with:
          PROJECT_FILE_PATH: Solnet.Serum/Solnet.Serum.csproj
          PACKAGE_NAME: Solnet.Serum
          VERSION_STATIC: ${{ env.BUILD_VERSION }}
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true 