name: Build, Pack & Publish

on:
  push:
    branches:
      - master # Default release branch
      - net5 # .NET 5 release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Extract release notes
        run: |
            git log --pretty=format:'%s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES.txt
      - name: Run the build script
        uses: cake-build/cake-action@v1
        with:
          script-path: build.cake
          target: Pack
          cake-bootstrap: true
      - name: Publish on version change
        id: publish_nuget
        uses: bmresearch/publish-nuget@master
        with:
          PROJECT_FILE_PATH: Solnet.Serum/Solnet.Serum.csproj
          PACKAGE_NAME: Solnet.Serum
          VERSION_FILE_PATH: SharedBuildProperties.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.publish_nuget.outputs.VERSION }}
          release_name: ${{ steps.publish_nuget.outputs.VERSION }}
          body_path: RELEASE-NOTES.txt
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: artifacts/Solnet.Serum.dll
          tag: ${{ steps.publish_nuget.outputs.VERSION }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}